import { setWorkersEnv } from "../src/lib/workers-env";
import type { ExecutionContext, ExportedHandler, ScheduledController } from "./worker-types";
import { runScheduledJob } from "./scheduled";

// Generated by OpenNext at build time
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: generated by the OpenNext build.
import openNextWorker from "../.open-next/worker.js";

type Env = Record<string, unknown>;

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    setWorkersEnv(env);
    const fetchHandler = (openNextWorker as {
      fetch: (req: Request, env: Env, ctx: ExecutionContext) => Promise<Response>;
    }).fetch;
    return fetchHandler(request, env, ctx);
  },

  async scheduled(controller: ScheduledController, env: Env, ctx: ExecutionContext): Promise<void> {
    setWorkersEnv(env);
    ctx.waitUntil(runScheduledJob(controller));
  },
} satisfies ExportedHandler<Env>;
